# render.yaml
services:
  - type: web
    name: inventario-api
    env: python
    region: oregon
    plan: free # o tu plan actual
    buildCommand: |
      python3.11 -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      source .venv/bin/activate
      uvicorn app.main:app --host 0.0.0.0 --port 10000
    pythonVersion: "3.11"  # <-- clave, cambiar a 3.11
    envVars:
      - key: PORT
        value: "10000"